### ISSUE TITLE
Get access to instructors' resource

### ISSUE THREAD

**Issue by clark874** [UWNETLAB/dcss_supplementary#1]
Hi there. Thank you for contribute such a valuable textbook in this field. I have bought both the ebook and paper print version but found that I cannot get access to instructors' resource through https://study.sagepub.com/mclevey. I have wrote an email to SAGE but they did not reply. Is there anyway I can get access to such resource from you?

**Comment by mclevey** [comment]
Hi @clark874! Sorry, I am just seeing this now. Yes, I can provide those resources. Can you send me an email at john.mclevey@uwaterloo.ca with a link to the course you are offering? Thanks!

**Comment by clark874** [comment]
> 

Thank you for getting back to me. I'm a tutor designing for a new course in China so I may not have a link right now( since in our university there is no web link for a course like it is in Canada). Still, I can provide you with a tutor's email that I'm using which ends with edu.cn to show my identity.
