### ISSUE TITLE
Chapter 14 Leidenalg partition missing attribute

### ISSUE THREAD

**Issue by Minyall** [UWNETLAB/dcss_supplementary#12]
In Chapter 14, under 'From Louvain to Leiden' in the provided notebook, we're meant to run...

`partition = part.copy()
for membership, node in zip(part_leiden._membership, part_leiden._graph.vs['name']):
    partition[node] = membership`

However there is an attribute error raised from part_leiden._graph.vs['name']. It appears to be related specifically to the `name` key as there is an attribute `._graph.vs`. Running `._graph.vs.attribute_names()` and `._graph.vs.attributes()` both return empty lists implying there are no attributes at all associated with the `part_leiden` partition. We've experienced this on two different machines, one MacOS another Windows, so think it may possibly be a change in the Leidenalg package?

**Comment by pbrowne88** [comment]
I think you've already figured it out; I can't say for certain, but I suspect -- as you do -- that this stems from a versioning issue. We're currently in the process of rolling back all of the pacakges in the various environment files to versions that were current circa April 2021. With luck, that will fix the problem.

**Comment by pbrowne88** [comment]
The version rollback has been pushed to the repo, which should have solved this issue. I'm going to close it, but will re-open it if the same error or similar persists -- please let us know!
