### ISSUE TITLE
Revert packages in all environments to versions used at time of creation

### ISSUE THREAD

**Issue by pbrowne88** [UWNETLAB/dcss_supplementary#4]
Currently, the packages listed in all of the environments are not version-specific; there may be no issues currently, but the situation will eventually become untenable. It's imperative that the environments use a fixed set of versions that are compatible with each other and with the code in the book.

**Comment by pbrowne88** [comment]
This will also necessarily fix the `whatlies` problem mentioned #3

**Comment by mclevey** [comment]
Good catch!

**Comment by pbrowne88** [comment]
All package versions standardised
