### ISSUE TITLE
Size of repo may make lead to incomplete git clone

### ISSUE THREAD

**Issue by Minyall** [UWNETLAB/dcss_supplementary#7]
I've been trying to make a local clone of the repo but I have been recieving an error stating that 'the remote end hung up unexpectedly' which I believe is related to the repo size. It is commonly reported by others trying to clone large repos. It may be fixable by the user first adjusting their buffer size using `git config --global http.postBuffer 1048576000` however I'm yet to be succesful in cloning the repo even on high speed institutional internet after making these adjustments. Given the book begins with users cloning the repo, this may be a bit of a hurdle. Perhaps the largest files could be offloaded elsewhere to reduce size, and then add a helper function in the dcss pip package to download?

****EDIT****
Ok I realised that I needed to install git-lfs in order for the pretrained models to be handled properly by git clone. I didn't have this in my git installation. Now that it's installed it seems to be cloning ok, though taking a while. It may still be more accessible for students to not have the pretrained models by default for a quicker stand up process, but still make them available as an optional extra.

**Comment by mclevey** [comment]
Thanks, @Minyall! We've also realized it is due to LFS. I'm working on an alternative solution, and my students and I are doing a few other things to reduce the size of the repo. Should have something in place very soon.

**Comment by pbrowne88** [comment]
All `LFS` files in the repo have been removed; repository should download without issue -- even for those without `git-lfs` installed. The issue of providing the pre-trained models using a different venue remains unsolved; I've opened #13 accordingly.
