### ISSUE TITLE
Environment does not build on Apple Silicon

### ISSUE THREAD

**Issue by Minyall** [UWNETLAB/dcss_supplementary#8]
Due to `mkl` and tensorflow incompatibility with Apple Silicon CPUs the main environment.yml file will not result in a succesful build. I believe I have a working environment file and have that sucesfully completed the build but it may need testing on tensorflow tasks. I've issued a pull request #6 and am happy to do the testing if pointed in the right direction.

**Comment by mclevey** [comment]
Very glad you caught this; thank you! I've accepted your pull request. At the same time, we added another environment file and are looking to test it. I'll have some notebooks suitable for testing within a day or so. Thanks very much!

**Comment by Minyall** [comment]
Looks like the two environment files are identical. Great minds. Very happy to be the Apple Silicon guinea pig if you want to send over those notebooks.
